/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'engine.dll'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _GUID;
struct _s_ThrowInfo;
struct _s_CatchableTypeArray;
struct _s_CatchableType;
struct TypeDescriptor;
struct _SYSTEMTIME;
struct HWND__;
union _LARGE_INTEGER;
struct tagWNDCLASSA;
struct HINSTANCE__;
struct HICON__;
struct HBRUSH__;
struct _RTL_CRITICAL_SECTION_DEBUG;
struct _EXCEPTION_RECORD;
struct _CONTEXT;

/* 1 */
enum __TI_flags
{
  TI_IsConst = 0x1,
  TI_IsVolatile = 0x2,
  TI_IsUnaligned = 0x4,
  TI_IsPure = 0x8,
  TI_IsWinRT = 0x10,
};

/* 2 */
enum __CT_flags
{
  CT_IsSimpleType = 0x1,
  CT_ByReferenceOnly = 0x2,
  CT_HasVirtualBase = 0x4,
  CT_IsWinRTHandle = 0x8,
  CT_IsStdBadAlloc = 0x10,
};

/* 3 */
struct FuncInfo
{
  int magicNumber;
  int maxState;
  void *pUnwindMap;
  int nTryBlocks;
  void *pTryBlockMap;
  int nIPMapEntries;
  void *pIPtoStateMap;
  void *pESTypeList;
  int EHFlags;
};

/* 4 */
struct UnwindMapEntry
{
  int toState;
  void *action;
};

/* 5 */
struct TryBlockMapEntry
{
  int tryLow;
  int tryHigh;
  int catchHigh;
  int nCatches;
  void *pHandlerArray;
};

/* 6 */
struct HandlerType
{
  int adjectives;
  void *pType;
  int dispCatchObj;
  void *addressOfHandler;
};

/* 7 */
struct _EH4_SCOPETABLE_RECORD
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 38 */
typedef unsigned int DWORD;

/* 8 */
struct _EH4_SCOPETABLE
{
  DWORD GSCookieOffset;
  DWORD GSCookieXOROffset;
  DWORD EHCookieOffset;
  DWORD EHCookieXOROffset;
  struct _EH4_SCOPETABLE_RECORD ScopeRecord[];
};

/* 9 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 84 */
typedef void *PVOID;

/* 10 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 11 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 12 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 13 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 15 */
typedef int LONG;

/* 14 */
struct tagRECT
{
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};

/* 17 */
typedef unsigned int _dev_t;

/* 18 */
typedef unsigned __int16 _ino_t;

/* 19 */
typedef int _off_t;

/* 20 */
typedef int __time32_t;

/* 16 */
#pragma pack(push, 8)
struct _stat32
{
  _dev_t st_dev;
  _ino_t st_ino;
  unsigned __int16 st_mode;
  __int16 st_nlink;
  __int16 st_uid;
  __int16 st_gid;
  _dev_t st_rdev;
  _off_t st_size;
  __time32_t st_atime;
  __time32_t st_mtime;
  __time32_t st_ctime;
};
#pragma pack(pop)

/* 22 */
typedef _GUID GUID;

/* 21 */
typedef GUID IID;

/* 23 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 25 */
typedef const _s_ThrowInfo ThrowInfo;

/* 24 */
typedef ThrowInfo _ThrowInfo;

/* 27 */
typedef void (__cdecl *PMFN)(void *);

/* 28 */
typedef const _s_CatchableTypeArray CatchableTypeArray;

/* 26 */
#pragma pack(push, 4)
struct _s_ThrowInfo
{
  unsigned int attributes;
  PMFN pmfnUnwind;
  int (__cdecl *pForwardCompat)();
  CatchableTypeArray *pCatchableTypeArray;
};
#pragma pack(pop)

/* 30 */
typedef const _s_CatchableType CatchableType;

/* 29 */
#pragma pack(push, 4)
struct _s_CatchableTypeArray
{
  int nCatchableTypes;
  CatchableType *arrayOfCatchableTypes[];
};
#pragma pack(pop)

/* 33 */
#pragma pack(push, 4)
struct PMD
{
  int mdisp;
  int pdisp;
  int vdisp;
};
#pragma pack(pop)

/* 31 */
#pragma pack(push, 4)
struct _s_CatchableType
{
  unsigned int properties;
  TypeDescriptor *pType;
  PMD thisDisplacement;
  int sizeOrOffset;
  PMFN copyFunction;
};
#pragma pack(pop)

/* 32 */
#pragma pack(push, 4)
struct TypeDescriptor
{
  unsigned int hash;
  void *spare;
  char name[];
};
#pragma pack(pop)

/* 34 */
typedef _SYSTEMTIME SYSTEMTIME;

/* 36 */
typedef unsigned __int16 WORD;

/* 35 */
struct _SYSTEMTIME
{
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
};

/* 40 */
struct tagPOINT
{
  LONG x;
  LONG y;
};

/* 39 */
typedef tagPOINT POINT;

/* 41 */
typedef tagRECT RECT;

/* 37 */
struct tagCOMPOSITIONFORM
{
  DWORD dwStyle;
  POINT ptCurrentPos;
  RECT rcArea;
};

/* 43 */
typedef unsigned int _fsize_t;

/* 42 */
#pragma pack(push, 8)
struct _finddata32_t
{
  unsigned int attrib;
  __time32_t time_create;
  __time32_t time_access;
  __time32_t time_write;
  _fsize_t size;
  char name[260];
};
#pragma pack(pop)

/* 45 */
typedef HWND__ *HWND;

/* 47 */
typedef unsigned int UINT;

/* 49 */
typedef unsigned int UINT_PTR;

/* 48 */
typedef UINT_PTR WPARAM;

/* 51 */
typedef int LONG_PTR;

/* 50 */
typedef LONG_PTR LPARAM;

/* 44 */
struct tagMSG
{
  HWND hwnd;
  UINT message;
  WPARAM wParam;
  LPARAM lParam;
  DWORD time;
  POINT pt;
};

/* 46 */
struct HWND__
{
  int unused;
};

/* 54 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 53 */
typedef _FILETIME FILETIME;

/* 55 */
typedef char CHAR;

/* 52 */
struct _WIN32_FIND_DATAA
{
  DWORD dwFileAttributes;
  FILETIME ftCreationTime;
  FILETIME ftLastAccessTime;
  FILETIME ftLastWriteTime;
  DWORD nFileSizeHigh;
  DWORD nFileSizeLow;
  DWORD dwReserved0;
  DWORD dwReserved1;
  CHAR cFileName[260];
  CHAR cAlternateFileName[14];
};

/* 56 */
typedef _LARGE_INTEGER LARGE_INTEGER;

/* 58 */
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};

/* 59 */
typedef __int64 LONGLONG;

/* 57 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  LONGLONG QuadPart;
};

/* 60 */
typedef tagWNDCLASSA WNDCLASSA;

/* 63 */
typedef LONG_PTR LRESULT;

/* 62 */
typedef LRESULT (__stdcall *WNDPROC)(HWND, UINT, WPARAM, LPARAM);

/* 64 */
typedef HINSTANCE__ *HINSTANCE;

/* 66 */
typedef HICON__ *HICON;

/* 68 */
typedef HICON HCURSOR;

/* 69 */
typedef HBRUSH__ *HBRUSH;

/* 71 */
typedef const CHAR *LPCSTR;

/* 61 */
struct tagWNDCLASSA
{
  UINT style;
  WNDPROC lpfnWndProc;
  int cbClsExtra;
  int cbWndExtra;
  HINSTANCE hInstance;
  HICON hIcon;
  HCURSOR hCursor;
  HBRUSH hbrBackground;
  LPCSTR lpszMenuName;
  LPCSTR lpszClassName;
};

/* 65 */
struct HINSTANCE__
{
  int unused;
};

/* 67 */
struct HICON__
{
  int unused;
};

/* 70 */
struct HBRUSH__
{
  int unused;
};

/* 73 */
typedef _RTL_CRITICAL_SECTION_DEBUG *PRTL_CRITICAL_SECTION_DEBUG;

/* 77 */
typedef void *HANDLE;

/* 78 */
typedef unsigned int ULONG_PTR;

/* 72 */
#pragma pack(push, 8)
struct _RTL_CRITICAL_SECTION
{
  PRTL_CRITICAL_SECTION_DEBUG DebugInfo;
  LONG LockCount;
  LONG RecursionCount;
  HANDLE OwningThread;
  HANDLE LockSemaphore;
  ULONG_PTR SpinCount;
};
#pragma pack(pop)

/* 76 */
struct _LIST_ENTRY
{
  _LIST_ENTRY *Flink;
  _LIST_ENTRY *Blink;
};

/* 75 */
typedef _LIST_ENTRY LIST_ENTRY;

/* 74 */
struct _RTL_CRITICAL_SECTION_DEBUG
{
  WORD Type;
  WORD CreatorBackTraceIndex;
  _RTL_CRITICAL_SECTION *CriticalSection;
  LIST_ENTRY ProcessLocksList;
  DWORD EntryCount;
  DWORD ContentionCount;
  DWORD Flags;
  WORD CreatorBackTraceIndexHigh;
  WORD SpareWORD;
};

/* 79 */
#pragma pack(push, 8)
struct tm
{
  int tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
};
#pragma pack(pop)

/* 82 */
typedef _EXCEPTION_RECORD EXCEPTION_RECORD;

/* 81 */
typedef EXCEPTION_RECORD *PEXCEPTION_RECORD;

/* 86 */
typedef _CONTEXT CONTEXT;

/* 85 */
typedef CONTEXT *PCONTEXT;

/* 80 */
struct _EXCEPTION_POINTERS
{
  PEXCEPTION_RECORD ExceptionRecord;
  PCONTEXT ContextRecord;
};

/* 83 */
struct _EXCEPTION_RECORD
{
  DWORD ExceptionCode;
  DWORD ExceptionFlags;
  _EXCEPTION_RECORD *ExceptionRecord;
  PVOID ExceptionAddress;
  DWORD NumberParameters;
  ULONG_PTR ExceptionInformation[15];
};

/* 90 */
typedef unsigned __int8 BYTE;

/* 89 */
struct _FLOATING_SAVE_AREA
{
  DWORD ControlWord;
  DWORD StatusWord;
  DWORD TagWord;
  DWORD ErrorOffset;
  DWORD ErrorSelector;
  DWORD DataOffset;
  DWORD DataSelector;
  BYTE RegisterArea[80];
  DWORD Spare0;
};

/* 88 */
typedef _FLOATING_SAVE_AREA FLOATING_SAVE_AREA;

/* 87 */
#pragma pack(push, 4)
struct _CONTEXT
{
  DWORD ContextFlags;
  DWORD Dr0;
  DWORD Dr1;
  DWORD Dr2;
  DWORD Dr3;
  DWORD Dr6;
  DWORD Dr7;
  FLOATING_SAVE_AREA FloatSave;
  DWORD SegGs;
  DWORD SegFs;
  DWORD SegEs;
  DWORD SegDs;
  DWORD Edi;
  DWORD Esi;
  DWORD Ebx;
  DWORD Edx;
  DWORD Ecx;
  DWORD Eax;
  DWORD Ebp;
  DWORD Eip;
  DWORD SegCs;
  DWORD EFlags;
  DWORD Esp;
  DWORD SegSs;
  BYTE ExtendedRegisters[512];
};
#pragma pack(pop)

/* 91 */
struct KSG_LogFile;

/* 92 */
struct KDirectDraw;

/* 93 */
struct KSprite;

/* 94 */
struct KAviFile;

/* 95 */
struct tagBITMAPINFOHEADER
{
  DWORD biSize;
  LONG biWidth;
  LONG biHeight;
  WORD biPlanes;
  WORD biBitCount;
  DWORD biCompression;
  DWORD biSizeImage;
  LONG biXPelsPerMeter;
  LONG biYPelsPerMeter;
  DWORD biClrUsed;
  DWORD biClrImportant;
};

/* 96 */
struct KNode;

/* 97 */
struct KTgaFile32;

/* 98 */
struct KTabFile;

/* 99 */
struct KList;

/* 100 */
struct KCanvas;

/* 101 */
struct KBitmap;

/* 102 */
struct KFindBinTreeNode;

/* 103 */
struct KPcxFile;

/* 104 */
struct KBitmap16;

/* 105 */
struct KBmp2Spr;

/* 106 */
struct KStrNode;

/* 107 */
struct KCache;

/* 108 */
struct KCodec;

/* 109 */
struct KCodecLzo;

/* 110 */
struct KDirectInput;

/* 111 */
struct KDirectSound;

/* 112 */
struct KScript;

/* 113 */
struct KEicScript;

/* 114 */
struct KLuaScript;

/* 115 */
struct KLuaCall;

/* 116 */
struct KScriptSet;

/* 117 */
struct KEicScriptSet;

/* 118 */
struct KFileDialog;

/* 119 */
struct KFont;

/* 120 */
struct KWin32App;

/* 121 */
struct KEvent;

/* 122 */
struct KThread;

/* 123 */
struct KFindBinTree;

/* 124 */
struct KGifFile;

/* 125 */
struct KThread2;

/* 126 */
struct KHashNode;

/* 127 */
struct KIme;

/* 128 */
struct KKeyboard;

/* 129 */
struct KLinkArray;

/* 130 */
struct KLuaScriptSet;

/* 131 */
struct KPakTool;

/* 132 */
struct KMemClass;

/* 133 */
struct KMemManager;

/* 134 */
struct KMemStack;

/* 135 */
struct KMouse;

/* 136 */
struct KMusic;

/* 137 */
struct KMp3Music;

/* 138 */
struct KMp4Audio;

/* 139 */
struct KVideo;

/* 140 */
struct KMp4Video;

/* 141 */
struct KMp4Movie;

/* 142 */
struct KMpgMusic;

/* 143 */
struct KMsgNode;

/* 144 */
struct KMutex;

/* 145 */
struct KOctreeNode;

/* 146 */
struct KOctree;

/* 147 */
struct KPolygon;

/* 148 */
struct KSafeList;

/* 149 */
struct KScanFile;

/* 150 */
struct TBinTreeNode;

/* 151 */
struct KMemFile;

/* 152 */
struct KSortBinTree;

/* 153 */
struct KSortList;

/* 154 */
struct KSoundCache;

/* 155 */
struct KSpriteCache;

/* 156 */
struct KSpriteCodec;

/* 157 */
struct KSpriteMaker;

/* 158 */
struct KStrList;

/* 159 */
struct KTimer;

/* 160 */
struct KWavFile;

/* 161 */
#pragma pack(push, 1)
struct tWAVEFORMATEX
{
  WORD wFormatTag;
  WORD nChannels;
  DWORD nSamplesPerSec;
  DWORD nAvgBytesPerSec;
  WORD nBlockAlign;
  WORD wBitsPerSample;
  WORD cbSize;
};
#pragma pack(pop)

/* 162 */
struct KWavMusic;

/* 163 */
struct KWavSound;

/* 164 */
struct KZipCodec;

/* 165 */
struct KZipList;

/* 166 */
struct KZipFile;

/* 167 */
struct KFile;

/* 168 */
struct KIniFile;

/* 169 */
struct KZipData;

/* 170 */
struct KPakData;

/* 171 */
struct KPakFile;

/* 172 */
struct KITabFile;

/* 173 */
struct KTabFileCtrl;

/* 174 */
struct XPackFilePartner;

/* 175 */
struct std::exception;

/* 176 */
struct type_info;

/* 177 */
struct KAutoMutex;

/* 178 */
struct KBmpFile;

/* 179 */
struct KBmpFile24;

/* 180 */
struct KHashTable;

/* 181 */
struct KMemClass1;

/* 182 */
struct std::nothrow_t;

/* 183 */
struct KJpgFile;

